---
- name: Install the latest version of Apache
  become: true
  yum:
    name: httpd
    state: present

- name: Start service httpd, if not started
  become: true
  service:
    name: httpd
    state: started
